package gin

var HandlerTemplateText = `// Code generated by thriftgo-tools/cmd/httpgen v{{ .Version }}. DO NOT EDIT.
package {{ .PkgName }}

import (
	"net/http"

	"github.com/bytedance/go-tagexpr/v2/binding"
	"github.com/gin-gonic/gin"
	{{ range .Imports }}
	"{{ . }}"{{ end }}
)

type Handler struct {
	service {{ .ServiceTypeName }}
}

func NewHandler(service {{ .ServiceTypeName }}) *Handler {
	return &Handler{service: service}
}

{{ range .Handlers }}
{{ if ne .HTTPMethod "" }}
func (h *Handler) {{ .HandlerFuncName }}(ctx *gin.Context) {
	var err error
	var req {{ .RequestTypeName }}
	err = binding.BindAndValidate(&req, ctx.Request, ctx.Params)
	if err != nil {
		ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	resp, err := h.service.{{ .HandlerFuncName }}(ctx, &req)
	if err != nil {
		return
	}

	ctx.JSON(http.StatusOK, resp)
}
{{ end }}
{{ end }}`
