package gin

var RouterHeadTemplateText = `// Code generated by thriftgo-tools v{{ .Version }}.
package {{ .PkgName }}

import (
	"github.com/gin-gonic/gin"
)

func Register(router gin.IRouter, service {{ .ServiceTypeName }}) {
	handler := NewHandler(service)
	// @route_gen begin{{ InsertionPoint .PkgName "Register" }}// @route_gen end
}`

var RouterTemplateText = `{{- range .Handlers }}{{- if ne .HTTPMethod "" }}
	router.{{ .HTTPMethod }}("{{ .Route }}", handler.{{ .HandlerFuncName }})
{{- end }}{{- end }}
`
