package gin

var ServiceTemplateText = `// Code generated by thriftgo-http-plugin v{{ .Version }}.
package {{ .PkgName }}

import (
	"context"
	{{ range .Imports }}"{{ . }}"{{ end }}
	{{ .PkgPath }}
)

type Service struct{}

{{ range .Handlers }}
func (s *Service) {{ .HandlerFuncName }}(ctx context.Context, req *{{ .RequestTypeName }}) (r *{{ .ResponseTypeName }}, err error) {
	// Write biz code here.
	return
}
{{ end }}`
